apiVersion: "nais.io/v1alpha1"
kind: "Application"
metadata:
  annotations:
    dp_name: dataproductname
    dp_description: "fantastically fine description"
  name: hello-world
  namespace: aura
  labels:
    team: aura
spec:
  image: ghcr.io/nais/hello-world:1

  gcp:
    buckets:
      - name: dataproductbucket
  ingresses:
  - https://hello-world.dev.nav.no
