apiVersion: "nais.io/v1alpha1"
kind: "Application"
metadata:
  annotations:
    dp_name: dataproduct
    dp_description: "fantastically fine description"
  name: hello-world-1
  namespace: aura
  labels:
    team: aura
spec:
  image: ghcr.io/nais/hello-world:1
  gcp:
    buckets:
      - name: anotherbucket
  ingresses:
  - https://hello-world.dev.nav.no
